apiVersion: v1
kind: Pod
metadata:
  name: node1
  labels:
    apps: nodes
spec:
  containers:
    - name: node0
      image: parity/parity:v2.5.13-stable
      command: [ "/bin/parity","--config"]
      args: ["/home/parity/config/node1.toml"]
      #command: [ "/bin/openethereum account new --config /home/parity/config/node0.toml"] # --keys-path /tmp/parity"]

      volumeMounts:
      - name: chain
        mountPath: /home/parity/chain
        readOnly: true
      - name: config
        mountPath: /home/parity/config
        readOnly: true
      - name: pwds
        mountPath: /home/parity/pwds
        readOnly: true
  volumes:
    - name: chain
      configMap:
        name: demo-spec
    - name: config
      configMap:
        name: node1
    - name: pwds
      configMap:
        name: nodepwds
  restartPolicy: Never
