apiVersion: v1
kind: Service
metadata:
  name: parity-test
  labels:
    app: parity-test
spec:
  ports:
  - port: 30303
    protocol: TCP
    name: tcp30303
  - port: 30303
    protocol: UDP
    name: udp30303
  - port: 5001
    name: p5001
  - port: 8080
    name: p8080
  - port: 8082
    name: p8082
  - port: 8083
    name: p8083
  - port: 8180
    name: p8180
  - port: 8545
    name: p8545
  - port: 8546
    name: p8546
  clusterIP: None
  selector:
    app: parity-test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: parity-test
spec:
  selector:
    matchLabels:
      app: parity-test
  serviceName: "parity-test"
  replicas: 1
  template:
    metadata:
      labels:
        app: parity-test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: parity
        image: parity/parity:v2.5.13-stable
        ports:
        - containerPort: 30303
          protocol: TCP
          name: tcp30303
        - containerPort: 30303
          protocol: UDP
          name: udp30303
        - containerPort: 5001
          name: p5001
        - containerPort: 8080
          name: p8080
        - containerPort: 8082
          name: p8082
        - containerPort: 8083
          name: p8083
        - containerPort: 8180
          name: p8180
        - containerPort: 8545
          name: p8545
        - containerPort: 8546
          name: p8546
        
